packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  # React 19
  react: ^19.2.0
  react-dom: ^19.2.0
  '@types/react': ^19.2.7
  '@types/react-dom': ^19.2.3

  # TanStack Router & Query (compatible versions)
  '@tanstack/react-router': ^1.139.10
  '@tanstack/react-router-devtools': ^1.139.10
  '@tanstack/router-plugin': ^1.139.12
  '@tanstack/router-cli': ^1.139.14
  '@tanstack/react-query': ^5.90.11
  '@tanstack/react-query-devtools': ^5.91.1
  '@tanstack/react-table': ^8.21.3

  # Form & Validation
  react-hook-form: ^7.66.1
  '@hookform/resolvers': ^5.2.2
  zod: ^4.1.13

  # Radix UI Components
  '@radix-ui/react-alert-dialog': ^1.1.15
  '@radix-ui/react-avatar': ^1.1.11
  '@radix-ui/react-checkbox': ^1.3.3
  '@radix-ui/react-collapsible': ^1.1.12
  '@radix-ui/react-dialog': ^1.1.15
  '@radix-ui/react-direction': ^1.1.1
  '@radix-ui/react-dropdown-menu': ^2.1.16
  '@radix-ui/react-label': ^2.1.8
  '@radix-ui/react-popover': ^1.1.15
  '@radix-ui/react-radio-group': ^1.3.8
  '@radix-ui/react-select': ^2.2.6
  '@radix-ui/react-separator': ^1.1.8
  '@radix-ui/react-slot': ^1.2.4
  '@radix-ui/react-tabs': ^1.1.13
  '@radix-ui/react-tooltip': ^1.2.8

  # Styling
  tailwindcss: ^4.1.17
  '@tailwindcss/vite': ^4.1.17
  clsx: ^2.1.1
  tailwind-merge: ^3.4.0
  class-variance-authority: ^0.7.1
  tw-animate-css: ^1.4.0

  # Icons & UI Utils
  lucide-react: ^0.552.0
  cmdk: ^1.1.1

  # Date & Time
  dayjs: ^1.11.19
  date-fns: ^4.1.0
  react-datepicker: ^8.2.0

  # HTTP Client
  axios: ^1.13.2

  # State Management
  zustand: ^5.0.8

  # Error Handling
  react-error-boundary: ^6.0.0

  # Utils
  lodash-es: ^4.17.21
  '@types/lodash-es': ^4.17.12
  uuid: ^13.0.0
  '@types/uuid': ^11.0.0

  # CKEditor
  '@ckeditor/ckeditor5-react': ^6.1.0

  # Build Tools & Vite
  vite: ^7.2.4
  '@vitejs/plugin-react': ^5.1.1
  '@vitejs/plugin-react-swc': ^4.2.1
  vite-plugin-dts: ^4.3.0
  vite-bundle-analyzer: ^1.2.3
  rollup-plugin-visualizer: ^6.0.5

  # TypeScript
  typescript: ~5.9.3
  '@types/node': ^24.10.1

  # React Compiler
  babel-plugin-react-compiler: 1.0.0

  # Storybook
  storybook: ^8.6.14
  '@storybook/addon-essentials': ^8.6.14
  '@storybook/addon-interactions': ^8.6.14
  '@storybook/addon-links': ^8.6.14
  '@storybook/addon-onboarding': ^8.6.14
  '@storybook/blocks': ^8.6.14
  '@storybook/react': ^8.6.14
  '@storybook/react-vite': ^8.6.14
  '@storybook/test': ^8.6.14
  '@chromatic-com/storybook': ^3.2.2

  # Testing & Development
  '@faker-js/faker': ^10.1.0

  # Linting & Formatting
  husky: ^9.1.7
  lint-staged: ^16.2.7

  # Monorepo
  turbo: ^2.6.1
