/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as PublicRouteImport } from './pages/_public'
import { Route as AuthenticatedRouteImport } from './pages/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './pages/_authenticated/index'
import { Route as PublicTestRouteImport } from './pages/_public/test'
import { Route as PublicLoginRouteImport } from './pages/_public/login'
import { Route as PublicAboutRouteImport } from './pages/_public/about'
import { Route as AuthenticatedReportIndexRouteImport } from './pages/_authenticated/report/index'
import { Route as AuthenticatedMonitoringIndexRouteImport } from './pages/_authenticated/monitoring/index'
import { Route as AuthenticatedInquiryIndexRouteImport } from './pages/_authenticated/inquiry/index'
import { Route as AuthenticatedUserRegisterRouteImport } from './pages/_authenticated/user/register'
import { Route as AuthenticatedUserMessageRouteImport } from './pages/_authenticated/user/message'
import { Route as AuthenticatedUserListRouteImport } from './pages/_authenticated/user/list'
import { Route as AuthenticatedUserInsightRouteImport } from './pages/_authenticated/user/insight'
import { Route as AuthenticatedMyMindUsageRouteImport } from './pages/_authenticated/my-mind/usage'
import { Route as AuthenticatedMyMindSettlementRouteImport } from './pages/_authenticated/my-mind/settlement'
import { Route as AuthenticatedMyMindReportRouteImport } from './pages/_authenticated/my-mind/report'
import { Route as AuthenticatedMyMindMonitoringRouteImport } from './pages/_authenticated/my-mind/monitoring'
import { Route as AuthenticatedMyMindInvoiceRouteImport } from './pages/_authenticated/my-mind/invoice'
import { Route as AuthenticatedMyMindInquiryRouteImport } from './pages/_authenticated/my-mind/inquiry'
import { Route as AuthenticatedMyMindDashboardRouteImport } from './pages/_authenticated/my-mind/dashboard'
import { Route as AuthenticatedMyMindContractRouteImport } from './pages/_authenticated/my-mind/contract'
import { Route as AuthenticatedMyFoodSettlementRouteImport } from './pages/_authenticated/my-food/settlement'
import { Route as AuthenticatedMyFoodReportRouteImport } from './pages/_authenticated/my-food/report'
import { Route as AuthenticatedMyFoodOrderRouteImport } from './pages/_authenticated/my-food/order'
import { Route as AuthenticatedMyFoodMonitoringRouteImport } from './pages/_authenticated/my-food/monitoring'
import { Route as AuthenticatedMyFoodInvoiceRouteImport } from './pages/_authenticated/my-food/invoice'
import { Route as AuthenticatedMyFoodInquiryRouteImport } from './pages/_authenticated/my-food/inquiry'
import { Route as AuthenticatedMyFoodDeliveryRouteImport } from './pages/_authenticated/my-food/delivery'
import { Route as AuthenticatedMyFoodDashboardRouteImport } from './pages/_authenticated/my-food/dashboard'
import { Route as AuthenticatedMyBodySettlementRouteImport } from './pages/_authenticated/my-body/settlement'
import { Route as AuthenticatedMyBodyReportRouteImport } from './pages/_authenticated/my-body/report'
import { Route as AuthenticatedMyBodyMonitoringRouteImport } from './pages/_authenticated/my-body/monitoring'
import { Route as AuthenticatedMyBodyDashboardRouteImport } from './pages/_authenticated/my-body/dashboard'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const PublicTestRoute = PublicTestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRoute,
} as any)
const AuthenticatedReportIndexRoute =
  AuthenticatedReportIndexRouteImport.update({
    id: '/report/',
    path: '/report/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMonitoringIndexRoute =
  AuthenticatedMonitoringIndexRouteImport.update({
    id: '/monitoring/',
    path: '/monitoring/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInquiryIndexRoute =
  AuthenticatedInquiryIndexRouteImport.update({
    id: '/inquiry/',
    path: '/inquiry/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUserRegisterRoute =
  AuthenticatedUserRegisterRouteImport.update({
    id: '/user/register',
    path: '/user/register',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUserMessageRoute =
  AuthenticatedUserMessageRouteImport.update({
    id: '/user/message',
    path: '/user/message',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUserListRoute = AuthenticatedUserListRouteImport.update({
  id: '/user/list',
  path: '/user/list',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUserInsightRoute =
  AuthenticatedUserInsightRouteImport.update({
    id: '/user/insight',
    path: '/user/insight',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMyMindUsageRoute =
  AuthenticatedMyMindUsageRouteImport.update({
    id: '/my-mind/usage',
    path: '/my-mind/usage',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMyMindSettlementRoute =
  AuthenticatedMyMindSettlementRouteImport.update({
    id: '/my-mind/settlement',
    path: '/my-mind/settlement',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMyMindReportRoute =
  AuthenticatedMyMindReportRouteImport.update({
    id: '/my-mind/report',
    path: '/my-mind/report',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMyMindMonitoringRoute =
  AuthenticatedMyMindMonitoringRouteImport.update({
    id: '/my-mind/monitoring',
    path: '/my-mind/monitoring',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMyMindInvoiceRoute =
  AuthenticatedMyMindInvoiceRouteImport.update({
    id: '/my-mind/invoice',
    path: '/my-mind/invoice',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMyMindInquiryRoute =
  AuthenticatedMyMindInquiryRouteImport.update({
    id: '/my-mind/inquiry',
    path: '/my-mind/inquiry',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMyMindDashboardRoute =
  AuthenticatedMyMindDashboardRouteImport.update({
    id: '/my-mind/dashboard',
    path: '/my-mind/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMyMindContractRoute =
  AuthenticatedMyMindContractRouteImport.update({
    id: '/my-mind/contract',
    path: '/my-mind/contract',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMyFoodSettlementRoute =
  AuthenticatedMyFoodSettlementRouteImport.update({
    id: '/my-food/settlement',
    path: '/my-food/settlement',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMyFoodReportRoute =
  AuthenticatedMyFoodReportRouteImport.update({
    id: '/my-food/report',
    path: '/my-food/report',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMyFoodOrderRoute =
  AuthenticatedMyFoodOrderRouteImport.update({
    id: '/my-food/order',
    path: '/my-food/order',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMyFoodMonitoringRoute =
  AuthenticatedMyFoodMonitoringRouteImport.update({
    id: '/my-food/monitoring',
    path: '/my-food/monitoring',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMyFoodInvoiceRoute =
  AuthenticatedMyFoodInvoiceRouteImport.update({
    id: '/my-food/invoice',
    path: '/my-food/invoice',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMyFoodInquiryRoute =
  AuthenticatedMyFoodInquiryRouteImport.update({
    id: '/my-food/inquiry',
    path: '/my-food/inquiry',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMyFoodDeliveryRoute =
  AuthenticatedMyFoodDeliveryRouteImport.update({
    id: '/my-food/delivery',
    path: '/my-food/delivery',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMyFoodDashboardRoute =
  AuthenticatedMyFoodDashboardRouteImport.update({
    id: '/my-food/dashboard',
    path: '/my-food/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMyBodySettlementRoute =
  AuthenticatedMyBodySettlementRouteImport.update({
    id: '/my-body/settlement',
    path: '/my-body/settlement',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMyBodyReportRoute =
  AuthenticatedMyBodyReportRouteImport.update({
    id: '/my-body/report',
    path: '/my-body/report',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMyBodyMonitoringRoute =
  AuthenticatedMyBodyMonitoringRouteImport.update({
    id: '/my-body/monitoring',
    path: '/my-body/monitoring',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMyBodyDashboardRoute =
  AuthenticatedMyBodyDashboardRouteImport.update({
    id: '/my-body/dashboard',
    path: '/my-body/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/about': typeof PublicAboutRoute
  '/login': typeof PublicLoginRoute
  '/test': typeof PublicTestRoute
  '/': typeof AuthenticatedIndexRoute
  '/my-body/dashboard': typeof AuthenticatedMyBodyDashboardRoute
  '/my-body/monitoring': typeof AuthenticatedMyBodyMonitoringRoute
  '/my-body/report': typeof AuthenticatedMyBodyReportRoute
  '/my-body/settlement': typeof AuthenticatedMyBodySettlementRoute
  '/my-food/dashboard': typeof AuthenticatedMyFoodDashboardRoute
  '/my-food/delivery': typeof AuthenticatedMyFoodDeliveryRoute
  '/my-food/inquiry': typeof AuthenticatedMyFoodInquiryRoute
  '/my-food/invoice': typeof AuthenticatedMyFoodInvoiceRoute
  '/my-food/monitoring': typeof AuthenticatedMyFoodMonitoringRoute
  '/my-food/order': typeof AuthenticatedMyFoodOrderRoute
  '/my-food/report': typeof AuthenticatedMyFoodReportRoute
  '/my-food/settlement': typeof AuthenticatedMyFoodSettlementRoute
  '/my-mind/contract': typeof AuthenticatedMyMindContractRoute
  '/my-mind/dashboard': typeof AuthenticatedMyMindDashboardRoute
  '/my-mind/inquiry': typeof AuthenticatedMyMindInquiryRoute
  '/my-mind/invoice': typeof AuthenticatedMyMindInvoiceRoute
  '/my-mind/monitoring': typeof AuthenticatedMyMindMonitoringRoute
  '/my-mind/report': typeof AuthenticatedMyMindReportRoute
  '/my-mind/settlement': typeof AuthenticatedMyMindSettlementRoute
  '/my-mind/usage': typeof AuthenticatedMyMindUsageRoute
  '/user/insight': typeof AuthenticatedUserInsightRoute
  '/user/list': typeof AuthenticatedUserListRoute
  '/user/message': typeof AuthenticatedUserMessageRoute
  '/user/register': typeof AuthenticatedUserRegisterRoute
  '/inquiry': typeof AuthenticatedInquiryIndexRoute
  '/monitoring': typeof AuthenticatedMonitoringIndexRoute
  '/report': typeof AuthenticatedReportIndexRoute
}
export interface FileRoutesByTo {
  '/about': typeof PublicAboutRoute
  '/login': typeof PublicLoginRoute
  '/test': typeof PublicTestRoute
  '/': typeof AuthenticatedIndexRoute
  '/my-body/dashboard': typeof AuthenticatedMyBodyDashboardRoute
  '/my-body/monitoring': typeof AuthenticatedMyBodyMonitoringRoute
  '/my-body/report': typeof AuthenticatedMyBodyReportRoute
  '/my-body/settlement': typeof AuthenticatedMyBodySettlementRoute
  '/my-food/dashboard': typeof AuthenticatedMyFoodDashboardRoute
  '/my-food/delivery': typeof AuthenticatedMyFoodDeliveryRoute
  '/my-food/inquiry': typeof AuthenticatedMyFoodInquiryRoute
  '/my-food/invoice': typeof AuthenticatedMyFoodInvoiceRoute
  '/my-food/monitoring': typeof AuthenticatedMyFoodMonitoringRoute
  '/my-food/order': typeof AuthenticatedMyFoodOrderRoute
  '/my-food/report': typeof AuthenticatedMyFoodReportRoute
  '/my-food/settlement': typeof AuthenticatedMyFoodSettlementRoute
  '/my-mind/contract': typeof AuthenticatedMyMindContractRoute
  '/my-mind/dashboard': typeof AuthenticatedMyMindDashboardRoute
  '/my-mind/inquiry': typeof AuthenticatedMyMindInquiryRoute
  '/my-mind/invoice': typeof AuthenticatedMyMindInvoiceRoute
  '/my-mind/monitoring': typeof AuthenticatedMyMindMonitoringRoute
  '/my-mind/report': typeof AuthenticatedMyMindReportRoute
  '/my-mind/settlement': typeof AuthenticatedMyMindSettlementRoute
  '/my-mind/usage': typeof AuthenticatedMyMindUsageRoute
  '/user/insight': typeof AuthenticatedUserInsightRoute
  '/user/list': typeof AuthenticatedUserListRoute
  '/user/message': typeof AuthenticatedUserMessageRoute
  '/user/register': typeof AuthenticatedUserRegisterRoute
  '/inquiry': typeof AuthenticatedInquiryIndexRoute
  '/monitoring': typeof AuthenticatedMonitoringIndexRoute
  '/report': typeof AuthenticatedReportIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_public/about': typeof PublicAboutRoute
  '/_public/login': typeof PublicLoginRoute
  '/_public/test': typeof PublicTestRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/my-body/dashboard': typeof AuthenticatedMyBodyDashboardRoute
  '/_authenticated/my-body/monitoring': typeof AuthenticatedMyBodyMonitoringRoute
  '/_authenticated/my-body/report': typeof AuthenticatedMyBodyReportRoute
  '/_authenticated/my-body/settlement': typeof AuthenticatedMyBodySettlementRoute
  '/_authenticated/my-food/dashboard': typeof AuthenticatedMyFoodDashboardRoute
  '/_authenticated/my-food/delivery': typeof AuthenticatedMyFoodDeliveryRoute
  '/_authenticated/my-food/inquiry': typeof AuthenticatedMyFoodInquiryRoute
  '/_authenticated/my-food/invoice': typeof AuthenticatedMyFoodInvoiceRoute
  '/_authenticated/my-food/monitoring': typeof AuthenticatedMyFoodMonitoringRoute
  '/_authenticated/my-food/order': typeof AuthenticatedMyFoodOrderRoute
  '/_authenticated/my-food/report': typeof AuthenticatedMyFoodReportRoute
  '/_authenticated/my-food/settlement': typeof AuthenticatedMyFoodSettlementRoute
  '/_authenticated/my-mind/contract': typeof AuthenticatedMyMindContractRoute
  '/_authenticated/my-mind/dashboard': typeof AuthenticatedMyMindDashboardRoute
  '/_authenticated/my-mind/inquiry': typeof AuthenticatedMyMindInquiryRoute
  '/_authenticated/my-mind/invoice': typeof AuthenticatedMyMindInvoiceRoute
  '/_authenticated/my-mind/monitoring': typeof AuthenticatedMyMindMonitoringRoute
  '/_authenticated/my-mind/report': typeof AuthenticatedMyMindReportRoute
  '/_authenticated/my-mind/settlement': typeof AuthenticatedMyMindSettlementRoute
  '/_authenticated/my-mind/usage': typeof AuthenticatedMyMindUsageRoute
  '/_authenticated/user/insight': typeof AuthenticatedUserInsightRoute
  '/_authenticated/user/list': typeof AuthenticatedUserListRoute
  '/_authenticated/user/message': typeof AuthenticatedUserMessageRoute
  '/_authenticated/user/register': typeof AuthenticatedUserRegisterRoute
  '/_authenticated/inquiry/': typeof AuthenticatedInquiryIndexRoute
  '/_authenticated/monitoring/': typeof AuthenticatedMonitoringIndexRoute
  '/_authenticated/report/': typeof AuthenticatedReportIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/about'
    | '/login'
    | '/test'
    | '/'
    | '/my-body/dashboard'
    | '/my-body/monitoring'
    | '/my-body/report'
    | '/my-body/settlement'
    | '/my-food/dashboard'
    | '/my-food/delivery'
    | '/my-food/inquiry'
    | '/my-food/invoice'
    | '/my-food/monitoring'
    | '/my-food/order'
    | '/my-food/report'
    | '/my-food/settlement'
    | '/my-mind/contract'
    | '/my-mind/dashboard'
    | '/my-mind/inquiry'
    | '/my-mind/invoice'
    | '/my-mind/monitoring'
    | '/my-mind/report'
    | '/my-mind/settlement'
    | '/my-mind/usage'
    | '/user/insight'
    | '/user/list'
    | '/user/message'
    | '/user/register'
    | '/inquiry'
    | '/monitoring'
    | '/report'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/login'
    | '/test'
    | '/'
    | '/my-body/dashboard'
    | '/my-body/monitoring'
    | '/my-body/report'
    | '/my-body/settlement'
    | '/my-food/dashboard'
    | '/my-food/delivery'
    | '/my-food/inquiry'
    | '/my-food/invoice'
    | '/my-food/monitoring'
    | '/my-food/order'
    | '/my-food/report'
    | '/my-food/settlement'
    | '/my-mind/contract'
    | '/my-mind/dashboard'
    | '/my-mind/inquiry'
    | '/my-mind/invoice'
    | '/my-mind/monitoring'
    | '/my-mind/report'
    | '/my-mind/settlement'
    | '/my-mind/usage'
    | '/user/insight'
    | '/user/list'
    | '/user/message'
    | '/user/register'
    | '/inquiry'
    | '/monitoring'
    | '/report'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_public'
    | '/_public/about'
    | '/_public/login'
    | '/_public/test'
    | '/_authenticated/'
    | '/_authenticated/my-body/dashboard'
    | '/_authenticated/my-body/monitoring'
    | '/_authenticated/my-body/report'
    | '/_authenticated/my-body/settlement'
    | '/_authenticated/my-food/dashboard'
    | '/_authenticated/my-food/delivery'
    | '/_authenticated/my-food/inquiry'
    | '/_authenticated/my-food/invoice'
    | '/_authenticated/my-food/monitoring'
    | '/_authenticated/my-food/order'
    | '/_authenticated/my-food/report'
    | '/_authenticated/my-food/settlement'
    | '/_authenticated/my-mind/contract'
    | '/_authenticated/my-mind/dashboard'
    | '/_authenticated/my-mind/inquiry'
    | '/_authenticated/my-mind/invoice'
    | '/_authenticated/my-mind/monitoring'
    | '/_authenticated/my-mind/report'
    | '/_authenticated/my-mind/settlement'
    | '/_authenticated/my-mind/usage'
    | '/_authenticated/user/insight'
    | '/_authenticated/user/list'
    | '/_authenticated/user/message'
    | '/_authenticated/user/register'
    | '/_authenticated/inquiry/'
    | '/_authenticated/monitoring/'
    | '/_authenticated/report/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_public/test': {
      id: '/_public/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof PublicTestRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_authenticated/report/': {
      id: '/_authenticated/report/'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof AuthenticatedReportIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/monitoring/': {
      id: '/_authenticated/monitoring/'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof AuthenticatedMonitoringIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inquiry/': {
      id: '/_authenticated/inquiry/'
      path: '/inquiry'
      fullPath: '/inquiry'
      preLoaderRoute: typeof AuthenticatedInquiryIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/user/register': {
      id: '/_authenticated/user/register'
      path: '/user/register'
      fullPath: '/user/register'
      preLoaderRoute: typeof AuthenticatedUserRegisterRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/user/message': {
      id: '/_authenticated/user/message'
      path: '/user/message'
      fullPath: '/user/message'
      preLoaderRoute: typeof AuthenticatedUserMessageRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/user/list': {
      id: '/_authenticated/user/list'
      path: '/user/list'
      fullPath: '/user/list'
      preLoaderRoute: typeof AuthenticatedUserListRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/user/insight': {
      id: '/_authenticated/user/insight'
      path: '/user/insight'
      fullPath: '/user/insight'
      preLoaderRoute: typeof AuthenticatedUserInsightRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my-mind/usage': {
      id: '/_authenticated/my-mind/usage'
      path: '/my-mind/usage'
      fullPath: '/my-mind/usage'
      preLoaderRoute: typeof AuthenticatedMyMindUsageRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my-mind/settlement': {
      id: '/_authenticated/my-mind/settlement'
      path: '/my-mind/settlement'
      fullPath: '/my-mind/settlement'
      preLoaderRoute: typeof AuthenticatedMyMindSettlementRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my-mind/report': {
      id: '/_authenticated/my-mind/report'
      path: '/my-mind/report'
      fullPath: '/my-mind/report'
      preLoaderRoute: typeof AuthenticatedMyMindReportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my-mind/monitoring': {
      id: '/_authenticated/my-mind/monitoring'
      path: '/my-mind/monitoring'
      fullPath: '/my-mind/monitoring'
      preLoaderRoute: typeof AuthenticatedMyMindMonitoringRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my-mind/invoice': {
      id: '/_authenticated/my-mind/invoice'
      path: '/my-mind/invoice'
      fullPath: '/my-mind/invoice'
      preLoaderRoute: typeof AuthenticatedMyMindInvoiceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my-mind/inquiry': {
      id: '/_authenticated/my-mind/inquiry'
      path: '/my-mind/inquiry'
      fullPath: '/my-mind/inquiry'
      preLoaderRoute: typeof AuthenticatedMyMindInquiryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my-mind/dashboard': {
      id: '/_authenticated/my-mind/dashboard'
      path: '/my-mind/dashboard'
      fullPath: '/my-mind/dashboard'
      preLoaderRoute: typeof AuthenticatedMyMindDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my-mind/contract': {
      id: '/_authenticated/my-mind/contract'
      path: '/my-mind/contract'
      fullPath: '/my-mind/contract'
      preLoaderRoute: typeof AuthenticatedMyMindContractRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my-food/settlement': {
      id: '/_authenticated/my-food/settlement'
      path: '/my-food/settlement'
      fullPath: '/my-food/settlement'
      preLoaderRoute: typeof AuthenticatedMyFoodSettlementRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my-food/report': {
      id: '/_authenticated/my-food/report'
      path: '/my-food/report'
      fullPath: '/my-food/report'
      preLoaderRoute: typeof AuthenticatedMyFoodReportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my-food/order': {
      id: '/_authenticated/my-food/order'
      path: '/my-food/order'
      fullPath: '/my-food/order'
      preLoaderRoute: typeof AuthenticatedMyFoodOrderRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my-food/monitoring': {
      id: '/_authenticated/my-food/monitoring'
      path: '/my-food/monitoring'
      fullPath: '/my-food/monitoring'
      preLoaderRoute: typeof AuthenticatedMyFoodMonitoringRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my-food/invoice': {
      id: '/_authenticated/my-food/invoice'
      path: '/my-food/invoice'
      fullPath: '/my-food/invoice'
      preLoaderRoute: typeof AuthenticatedMyFoodInvoiceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my-food/inquiry': {
      id: '/_authenticated/my-food/inquiry'
      path: '/my-food/inquiry'
      fullPath: '/my-food/inquiry'
      preLoaderRoute: typeof AuthenticatedMyFoodInquiryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my-food/delivery': {
      id: '/_authenticated/my-food/delivery'
      path: '/my-food/delivery'
      fullPath: '/my-food/delivery'
      preLoaderRoute: typeof AuthenticatedMyFoodDeliveryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my-food/dashboard': {
      id: '/_authenticated/my-food/dashboard'
      path: '/my-food/dashboard'
      fullPath: '/my-food/dashboard'
      preLoaderRoute: typeof AuthenticatedMyFoodDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my-body/settlement': {
      id: '/_authenticated/my-body/settlement'
      path: '/my-body/settlement'
      fullPath: '/my-body/settlement'
      preLoaderRoute: typeof AuthenticatedMyBodySettlementRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my-body/report': {
      id: '/_authenticated/my-body/report'
      path: '/my-body/report'
      fullPath: '/my-body/report'
      preLoaderRoute: typeof AuthenticatedMyBodyReportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my-body/monitoring': {
      id: '/_authenticated/my-body/monitoring'
      path: '/my-body/monitoring'
      fullPath: '/my-body/monitoring'
      preLoaderRoute: typeof AuthenticatedMyBodyMonitoringRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my-body/dashboard': {
      id: '/_authenticated/my-body/dashboard'
      path: '/my-body/dashboard'
      fullPath: '/my-body/dashboard'
      preLoaderRoute: typeof AuthenticatedMyBodyDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedMyBodyDashboardRoute: typeof AuthenticatedMyBodyDashboardRoute
  AuthenticatedMyBodyMonitoringRoute: typeof AuthenticatedMyBodyMonitoringRoute
  AuthenticatedMyBodyReportRoute: typeof AuthenticatedMyBodyReportRoute
  AuthenticatedMyBodySettlementRoute: typeof AuthenticatedMyBodySettlementRoute
  AuthenticatedMyFoodDashboardRoute: typeof AuthenticatedMyFoodDashboardRoute
  AuthenticatedMyFoodDeliveryRoute: typeof AuthenticatedMyFoodDeliveryRoute
  AuthenticatedMyFoodInquiryRoute: typeof AuthenticatedMyFoodInquiryRoute
  AuthenticatedMyFoodInvoiceRoute: typeof AuthenticatedMyFoodInvoiceRoute
  AuthenticatedMyFoodMonitoringRoute: typeof AuthenticatedMyFoodMonitoringRoute
  AuthenticatedMyFoodOrderRoute: typeof AuthenticatedMyFoodOrderRoute
  AuthenticatedMyFoodReportRoute: typeof AuthenticatedMyFoodReportRoute
  AuthenticatedMyFoodSettlementRoute: typeof AuthenticatedMyFoodSettlementRoute
  AuthenticatedMyMindContractRoute: typeof AuthenticatedMyMindContractRoute
  AuthenticatedMyMindDashboardRoute: typeof AuthenticatedMyMindDashboardRoute
  AuthenticatedMyMindInquiryRoute: typeof AuthenticatedMyMindInquiryRoute
  AuthenticatedMyMindInvoiceRoute: typeof AuthenticatedMyMindInvoiceRoute
  AuthenticatedMyMindMonitoringRoute: typeof AuthenticatedMyMindMonitoringRoute
  AuthenticatedMyMindReportRoute: typeof AuthenticatedMyMindReportRoute
  AuthenticatedMyMindSettlementRoute: typeof AuthenticatedMyMindSettlementRoute
  AuthenticatedMyMindUsageRoute: typeof AuthenticatedMyMindUsageRoute
  AuthenticatedUserInsightRoute: typeof AuthenticatedUserInsightRoute
  AuthenticatedUserListRoute: typeof AuthenticatedUserListRoute
  AuthenticatedUserMessageRoute: typeof AuthenticatedUserMessageRoute
  AuthenticatedUserRegisterRoute: typeof AuthenticatedUserRegisterRoute
  AuthenticatedInquiryIndexRoute: typeof AuthenticatedInquiryIndexRoute
  AuthenticatedMonitoringIndexRoute: typeof AuthenticatedMonitoringIndexRoute
  AuthenticatedReportIndexRoute: typeof AuthenticatedReportIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedMyBodyDashboardRoute: AuthenticatedMyBodyDashboardRoute,
  AuthenticatedMyBodyMonitoringRoute: AuthenticatedMyBodyMonitoringRoute,
  AuthenticatedMyBodyReportRoute: AuthenticatedMyBodyReportRoute,
  AuthenticatedMyBodySettlementRoute: AuthenticatedMyBodySettlementRoute,
  AuthenticatedMyFoodDashboardRoute: AuthenticatedMyFoodDashboardRoute,
  AuthenticatedMyFoodDeliveryRoute: AuthenticatedMyFoodDeliveryRoute,
  AuthenticatedMyFoodInquiryRoute: AuthenticatedMyFoodInquiryRoute,
  AuthenticatedMyFoodInvoiceRoute: AuthenticatedMyFoodInvoiceRoute,
  AuthenticatedMyFoodMonitoringRoute: AuthenticatedMyFoodMonitoringRoute,
  AuthenticatedMyFoodOrderRoute: AuthenticatedMyFoodOrderRoute,
  AuthenticatedMyFoodReportRoute: AuthenticatedMyFoodReportRoute,
  AuthenticatedMyFoodSettlementRoute: AuthenticatedMyFoodSettlementRoute,
  AuthenticatedMyMindContractRoute: AuthenticatedMyMindContractRoute,
  AuthenticatedMyMindDashboardRoute: AuthenticatedMyMindDashboardRoute,
  AuthenticatedMyMindInquiryRoute: AuthenticatedMyMindInquiryRoute,
  AuthenticatedMyMindInvoiceRoute: AuthenticatedMyMindInvoiceRoute,
  AuthenticatedMyMindMonitoringRoute: AuthenticatedMyMindMonitoringRoute,
  AuthenticatedMyMindReportRoute: AuthenticatedMyMindReportRoute,
  AuthenticatedMyMindSettlementRoute: AuthenticatedMyMindSettlementRoute,
  AuthenticatedMyMindUsageRoute: AuthenticatedMyMindUsageRoute,
  AuthenticatedUserInsightRoute: AuthenticatedUserInsightRoute,
  AuthenticatedUserListRoute: AuthenticatedUserListRoute,
  AuthenticatedUserMessageRoute: AuthenticatedUserMessageRoute,
  AuthenticatedUserRegisterRoute: AuthenticatedUserRegisterRoute,
  AuthenticatedInquiryIndexRoute: AuthenticatedInquiryIndexRoute,
  AuthenticatedMonitoringIndexRoute: AuthenticatedMonitoringIndexRoute,
  AuthenticatedReportIndexRoute: AuthenticatedReportIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface PublicRouteChildren {
  PublicAboutRoute: typeof PublicAboutRoute
  PublicLoginRoute: typeof PublicLoginRoute
  PublicTestRoute: typeof PublicTestRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAboutRoute: PublicAboutRoute,
  PublicLoginRoute: PublicLoginRoute,
  PublicTestRoute: PublicTestRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
